# Numpy Basics <hr style="border:2.5px solid #126782"></hr>

Data Analyst : Eugene John Mendez <br>
Department : Electrical Engineering 

In [30]:
# imports and packages 
import numpy as np 
from scipy import stats 

# Measures of Central Tendency 

# 1D Array

In [43]:
array_a = np.array ([1,2,3])
array_a

array([1, 2, 3])

# 2D Array 

In [45]:
my_array = np.array([
    [1,2,3], 
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
my_array = my_array.T
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [52]:
# add by row 
np.sum(my_array, axis=0)

array([ 6, 15])

In [53]:
# add by column 
np.sum(my_array, axis=1)

array([5, 7, 9])

In [31]:
fruits = np.array ([120, 60, 85, 150, 200 ])
fruits 

array([120,  60,  85, 150, 200])

In [32]:
fruits_mean = np.mean(fruits)
fruits_mean

123.0

In [33]:
median_fruits = np.median(fruits)
median_fruits 

120.0

In [34]:
mode_fruits = stats.mode (fruits)
mode_fruits 

ModeResult(mode=60, count=1)

In [35]:
jaguar = np.array ([10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [36]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

9.399999999999999

In [37]:
median_jaguar = np.median(jaguar)
median_jaguar  

9.8

In [61]:
mode_jaguar = stats.mode (jaguar)
mode_jaguar 

ModeResult(mode=9.8, count=2)

In [66]:
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)

range_jaguar = max_jaguar - min_jaguar
range_jaguar

8.0

In [67]:
q1_jaguar = np.percentile(jaguar,25)
q1_jaguar

9.4

In [68]:
# q2 median 
q2_jaguar = np.percentile(jaguar,50)
q2_jaguar

9.8

In [69]:
#Q3
q3_jaguar = np.percentile(jaguar,75)
q3_jaguar

10.45

In [70]:
#IQR 
iqr_jaguar = q3_jaguar - q1_jaguar
iqr_jaguar

1.049999999999999

In [87]:
var_jaguar = np.var(jaguar, ddof=1)
var_jaguar

4.86

In [73]:
std_jaguar = np.std(jaguar,ddof=1)
std_jaguar

2.2045407685048604

# Panther 

In [55]:
panther = np.array([10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1,])

In [63]:
mean_panther  = np.mean(panther)
mean_panther

10.75

In [60]:
median_panther = np.median(panther)
median_panther 

9.55

In [62]:
mode_panther = stats.mode (panther)
mode_panther

ModeResult(mode=9.1, count=3)

In [75]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther

10.9

In [77]:
q1_panther = np.percentile(panther,25)
q1_panther

9.125

In [79]:
q2_panther = np.percentile(panther,50)
q2_panther 

9.55

In [81]:
q3_panther = np.percentile(panther,75)
q3_panther 

10.625

In [83]:
iqr_panther = q3_panther - q1_panther
iqr_panther

1.5

In [89]:
var_panther = np.var(panther, ddof=1)
var_panther

11.082777777777777

In [90]:
std_panther = np.std(panther,ddof=1)
std_panther

3.3290806204983645